# Creating a Matrix



#### We've learned about vectors which allow us to store indexed elements. A matrix will allow us to have a 2-dimensional data structure which contains elements consisting of the same data type.

Before we talk about the Matrix, we should show a quick tip for quickly creating sequential numeric vectors, you can use the colon notation from slicing to create sequential vectors:

In [1]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

Great! Now, to create a matrix in R, you use the matrix() function. We can pass in a vector into the matrix:

In [3]:
matrix(v,2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Notice how the output is displayed. Here we have a two-dimensional matrix which is 10 rows by 1 column. Now what if we want to specify the number of rows? We can pass the parameter/argument into the matrix function called nrow which stands for number of rows:

In [4]:
matrix(data = v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Now we have a 2 by 5 matrix. Notice that the nrow argument allows this to happen. But how do we decide the fill order? We could have filed columns first (as we did above) or filled out the rows first insequential order. The byrow argument allows you to specify whether or not you want to fill out the matrix by rows or by columns. For example:

In [5]:
matrix(1:12,byrow = FALSE,nrow=4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [6]:
matrix(1:12, byrow=TRUE, nrow=4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [7]:
v

[1]  1  2  3  4  5  6  7  8  9 10

## Creating Matrices from Vectors

#### We can combine vectors to later input them into a matrix. For example imagine the following vectors below of stock prices:

In [8]:
# not real prices
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

In [9]:
stocks <- c(goog,msft)

In [10]:
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)


In [11]:
stock.matrix


[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

## Naming Matrices

Now that we have our matrix, it would be nice to name the rows and columns for reference. We can do this similarly to the names() function for vectors, but in this case we define colnames() and rownames(). So let's name our stock matrix:

In [12]:
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')

In [13]:
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

In [14]:
stock.matrix

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

## Matrix Arithmetic

#### We can perform element by element mathematical operations on a matrix with a scalar (single number) just like we could with vectors. Let's see some quick examples:

In [15]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [16]:
# Multiplication
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [17]:
# Division (reciprocal)
1/mat

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
[2,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.06250000
[3,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000 0.03846154
[4,] 0.03225806 0.03125000 0.03030303 0.02941176 0.02857143 0.02777778
[5,] 0.02439024 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913
     [,7]       [,8]       [,9]       [,10]     
[1,] 0.14285714 0.12500000 0.11111111 0.10000000
[2,] 0.05882353 0.05555556 0.05263158 0.05000000
[3,] 0.03703704 0.03571429 0.03448276 0.03333333
[4,] 0.02702703 0.02631579 0.02564103 0.02500000
[5,] 0.02127660 0.02083333 0.02040816 0.02000000

In [18]:
# Division
mat/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20   
[5,] 20.5 21   21.5 22   22.5 23   23.5 24   24.5 25

In [19]:
# Power
mat ^ 2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

## Comparison operators with matrices

#### We can similarly perform comparison operations across an entire matrix to return a matrix of logicals:

In [20]:
mat > 17

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

### Matrix Arithmetic with multiple matrices

#### We can use multiple matrices with arithmetic as well, for example:

In [21]:
mat + mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [22]:
mat / mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [23]:
# Warning, big numbers!
mat ^ mat

[,1]         [,2]         [,3]         [,4]         [,5]        
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[3,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34
[4,] 1.706917e+46 1.461502e+48 1.291100e+50 1.175664e+52 1.102507e+54
[5,] 1.330878e+66 1.501309e+68 1.734377e+70 2.050774e+72 2.480636e+74
     [,6]         [,7]         [,8]         [,9]         [,10]       
[1,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[2,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[3,] 6.156120e+36 4.434265e+38 3.314552e+40 2.567686e+42 2.058911e+44
[4,] 1.063874e+56 1.055513e+58 1.075912e+60 1.125951e+62 1.208926e+64
[5,] 3.068035e+76 3.877924e+78 5.007021e+80 6.600972e+82 8.881784e+84

In [24]:
mat*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

## Matrix multiplication

A quick side note on matrix multiplications. You can perform arithmetic multiplication on an element by element basis using the * sign in R. You should note this is not the same as Matrix Multiplication.
If you are familiar with the mathematics behind this topic and want to use R to perform true matrix multiplication, you can use the following:

In [25]:
mat2 <- matrix(1:9, nrow=3)

In [26]:
mat2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [27]:
# True Matrix Multiplication
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

Okay, that's it for matrices! Later on we will learn how to use factor() to quickly create categoical matrices from character elements.

## Matrix Operations

Now that we've learned how to create a matrix, let's learn how to use functions and perform operations on it!

Run the following code to create the stock.matrix from earlier

In [28]:
# Prices
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

# Put vectors into matrix
stocks <- c(goog,msft)
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)

# Name matrix
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

# Display
stock.matrix

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

In [29]:
colSums(stock.matrix)

Mon Tue Wed Thu Fri 
680 682 684 681 696

In [30]:
# Doesn't really make sense for stocks, but just to show how it works
rowSums(stock.matrix)

GOOG MSFT 
2266 1157

We can also do other mathematical operations, check this reference for all functions available.

In [31]:
rowMeans(stock.matrix)

GOOG  MSFT 
453.2 231.4

## Binding columns and rows

Let's go ahead and see how we can add columns and rows to a matrix, we can use the cbind() to bind a new column, and rbind() to bind a new row. For example, let's bind a new row with Facebook stock:

In [32]:
FB <- c(111,112,113,120,145)

In [33]:
tech.stocks <- rbind(stock.matrix,FB)

In [34]:
tech.stocks

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228
FB   111 112 113 120 145

Now let's add an average column to the matrix:

In [36]:
avg <- rowMeans(tech.stocks)

In [37]:
avg

GOOG  MSFT    FB 
453.2 231.4 120.2

In [38]:
tech.stocks <- cbind(tech.stocks,avg)

In [39]:
tech.stocks

Mon Tue Wed Thu Fri avg  
GOOG 450 451 452 445 468 453.2
MSFT 230 231 232 236 228 231.4
FB   111 112 113 120 145 120.2

## Matrix Selection and Indexing


Just like with vectors, we use the square bracket notation to select elements from a matrix. Since we have two dimensions to work with, we'll use a comma to separate our indexing for each dimension.

So the syntax is then:

In [40]:
# example.matrix[rows,columns]

where the index notation (e.g. 1:5) is put in place of the rows or columns . If either rows or columns is left blank, then we are selecting all the rows and columns.

Let's work through some examples:

In [41]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)

In [42]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [43]:
# Grab first row
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [44]:
#Grab first column
mat[,1]

[1]  1 11 21 31 41

In [45]:
# Grab first 3 rows
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [46]:
# Grab top left rectangle of:
# 1,2,3
# 11,12,13
#
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [47]:
# Grab last two columns
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [48]:
# Grab a center square of:
# 15,16
# 25,26
mat[2:3,5:6]

[,1] [,2]
[1,] 15   16  
[2,] 25   26

## Factor and Categorical Matrices

In this lecture we will discuss the factor() function and its use for creating categorical matrices. This specific function will become extremely useful when we begin to apply data analysis and machine learning techniques to our data, this idea is sometimes also known as creating dummy variables.

Let's start by showing an example of why and how we build this matrix. Imagine we have the following vectors representing data from an animal sanctuary for dogs ('d') and cats ('c') where they each have a corresponding id number in another vector.

In [49]:
animal <- c('d','c','d','c','c')
id <- c(1,2,3,4,5)

We want to convert the animal vector into information that an algorithm or equation can understand more easily. Meaning we want to begin to check how many categories (factor levels) are in our character vector.

We can pass the vector through the factor() function like so to get this information:

In [50]:
factor.ani <- factor(animal)

In [51]:
# Will show levels as well on RStudio or R Console
factor.ani

[1] d c d c c
Levels: c d

We can see that we have two levels, 'd' and 'c'. In R there are two distinct types of categorical variables, a ordinal categorical variable and a nominal categorical variable .

Nominal categorical variables don't have any order, such as dogs and cats (there is no order to them). Versus Ordinal categorical variables (as the name implies) do have an order. For example, if you had the vector:

In [52]:
ord.cat <- c('cold','med','hot')

You could begin to assign in order to these variables, such as:

cold < med < hot

if you wanted to assign an order while using the factor() function, you can pass in the arguments ordered=True and the pass in the levels= and pass in a vector in the order you want the levels to be in. So for example:

In [53]:
temps <- c('cold','med','cold','med','hot','hot','cold')
fact.temp <- factor(temps,ordered=TRUE,levels=c('cold','med','hot'))
fact.temp

[1] cold med  cold med  hot  hot  cold
Levels: cold < med < hot

This information is useful when used along with the summary() function which is an amazingly convenient function for quickly getting information from a matrix or vector. For example:

In [54]:
summary(temps)

   Length     Class      Mode 
        7 character character 

In [55]:
summary(fact.temp)

cold  med  hot 
   3    2    2